
MONGO_HOST = "127.0.0.1"
MONGO_PORT = 27017
DB_NAME = "local"
INPUT_COLLECTION = "export_adzuna_1500_uk"
CLEAN_COLLECTION = "clean_col"
PARTLY_CLEAN_COLLECTION = "partly_clean_col"
TAGS_COLLECTION = "tags_col"
NUM_PROCESSORS = 3
BATCH_SIZE = 200